/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vista;

import javax.swing.JOptionPane;

import Vista.jifVistaPedido;
import Vista.jifVistaProducto;
import Vista.jifVistaProveedor;
import Vista.jifVistaUsuario;

import Modelo.Cliente;
import Modelo.Proveedor;
import Modelo.Producto;
import Modelo.Pedido;

import Controlador.ControladorCliente;
import Controlador.ControladorProveedor;
import Controlador.ControladorProducto;
import Controlador.ControladorPedido;

/**
 *
 * @author Alfredo
 */
public class jDigMenu extends javax.swing.JDialog {

    /**
     * Creates new form jDigMenu
     */
    public jDigMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenuSalir = new javax.swing.JMenu();
        jimSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jimUsuario = new javax.swing.JMenuItem();
        jimProveedor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jimProducto = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jimPedido = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(181, 166, 112));
        jPanel2.setForeground(new java.awt.Color(181, 166, 112));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 724, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/home.png"))); // NOI18N
        jMenuSalir.setText("Inicio");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });

        jimSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/exit.png"))); // NOI18N
        jimSalir.setText("Salir");
        jimSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimSalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(jimSalir);

        jMenuBar2.add(jMenuSalir);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/registrar.png"))); // NOI18N
        jMenu2.setText("Registrarse");

        jimUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/new user.png"))); // NOI18N
        jimUsuario.setText("Usuario");
        jimUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimUsuarioActionPerformed(evt);
            }
        });
        jMenu2.add(jimUsuario);

        jimProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/proveedor.png"))); // NOI18N
        jimProveedor.setText("Proveedor");
        jimProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimProveedorActionPerformed(evt);
            }
        });
        jMenu2.add(jimProveedor);

        jMenuBar2.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/proveedor.png"))); // NOI18N
        jMenu4.setText("Proveedores");

        jimProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/producto.png"))); // NOI18N
        jimProducto.setText("Producto");
        jimProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimProductoActionPerformed(evt);
            }
        });
        jMenu4.add(jimProducto);

        jMenuBar2.add(jMenu4);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/user.png"))); // NOI18N
        jMenu3.setText("Usuarios");

        jimPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/carrito.png"))); // NOI18N
        jimPedido.setText("Pedido");
        jimPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jimPedidoActionPerformed(evt);
            }
        });
        jMenu3.add(jimPedido);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jimUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimUsuarioActionPerformed
        // TODO add your handling code here:
        Cliente cliente =new Cliente();
        jifVistaUsuario jifCli= new jifVistaUsuario();
        ControladorCliente controlador= new ControladorCliente(cliente, jifCli);

        jifCli.resize(740, 564); //redimensionar

        // Centrar
        java.awt.Dimension pantallaSize=this.jPanel2.getSize();
        java.awt.Dimension FrameSize =jifCli.getSize();
        jifCli.setLocation((pantallaSize.width-FrameSize.width)/2,(pantallaSize.height-FrameSize.height)/2);

        //mostrar
        this.jPanel2.add(jifCli);
        jifCli.show();
    }//GEN-LAST:event_jimUsuarioActionPerformed

    private void jimProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimProveedorActionPerformed
        // TODO add your handling code here:
        Proveedor pro =new Proveedor();
        jifVistaProveedor jifPro= new jifVistaProveedor();
        ControladorProveedor controlador= new ControladorProveedor(pro, jifPro);

        jifPro.resize(761, 590); //redimensionar

        // Centrar

        java.awt.Dimension pantallaSize=this.jPanel2.getSize();
        java.awt.Dimension FrameSize =jifPro.getSize();
        jifPro.setLocation((pantallaSize.width-FrameSize.width)/2,(pantallaSize.height-FrameSize.height)/2);

        //mostrar
        this.jPanel2.add(jifPro);
        jifPro.show();
    }//GEN-LAST:event_jimProveedorActionPerformed

    private void jimPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimPedidoActionPerformed
        // TODO add your handling code here:
        Pedido pe =new Pedido();
        jifVistaPedido jifPe= new jifVistaPedido();
        ControladorPedido controlador= new ControladorPedido(pe, jifPe);

        jifPe.resize(751, 740); //redimensionar

        // Centrar
        java.awt.Dimension pantallaSize=this.jPanel2.getSize();
        java.awt.Dimension FrameSize =jifPe.getSize();
        jifPe.setLocation((pantallaSize.width-FrameSize.width)/2,(pantallaSize.height-FrameSize.height)/2);
        

        //mostrar
        this.jPanel2.add(jifPe);
        jifPe.show();
    }//GEN-LAST:event_jimPedidoActionPerformed

    private void jimProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimProductoActionPerformed
        // TODO add your handling code here:
        Producto producto =new Producto();
        jifVistaProducto jifProducto= new jifVistaProducto();
        ControladorProducto controlador= new ControladorProducto(producto, jifProducto);

        jifProducto.resize(728, 632); //redimensionar

        // Centrar

        java.awt.Dimension pantallaSize=this.jPanel2.getSize();
        java.awt.Dimension FrameSize =jifProducto.getSize();
        jifProducto.setLocation((pantallaSize.width-FrameSize.width)/2,(pantallaSize.height-FrameSize.height)/2);

        //mostrar
        this.jPanel2.add(jifProducto);
        jifProducto.show();
    }//GEN-LAST:event_jimProductoActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jimSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jimSalirActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.YES_OPTION==JOptionPane.showConfirmDialog(this, "¿Desea Salir?","Sistema Ventas", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)){
            System.exit(0);

        }
    }//GEN-LAST:event_jimSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jDigMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jDigMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jDigMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jDigMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                jDigMenu dialog = new jDigMenu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenuItem jimPedido;
    private javax.swing.JMenuItem jimProducto;
    private javax.swing.JMenuItem jimProveedor;
    private javax.swing.JMenuItem jimSalir;
    private javax.swing.JMenuItem jimUsuario;
    // End of variables declaration//GEN-END:variables
}
