/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author andre
 */
public class jifVistaProveedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form jifVistaProveedor
     */
    public jifVistaProveedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        cmbComunidad = new javax.swing.JComboBox<>();
        btnCerrar = new javax.swing.JButton();
        txtUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jdcFecha = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProveedor = new javax.swing.JTable();
        txtNombres = new javax.swing.JTextField();
        txtRfc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(183, 168, 113));
        jPanel1.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(7, 68, 46));
        jLabel1.setText("Bienvenido Proveedor!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(167, 18, 480, 48);

        jLabel2.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(7, 68, 46));
        jLabel2.setText("Nombre(s)");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 180, 118, 24);

        jLabel3.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(7, 68, 46));
        jLabel3.setText("Correo");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 280, 77, 24);

        jLabel4.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(7, 68, 46));
        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 130, 88, 24);

        jLabel5.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(7, 68, 46));
        jLabel5.setText("Comunidad local");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(60, 430, 191, 24);

        jLabel6.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(7, 68, 46));
        jLabel6.setText("RFC");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(60, 380, 97, 24);

        txtApellido.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        txtApellido.setEnabled(false);
        txtApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoActionPerformed(evt);
            }
        });
        jPanel1.add(txtApellido);
        txtApellido.setBounds(230, 230, 276, 32);

        txtCorreo.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        txtCorreo.setEnabled(false);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo);
        txtCorreo.setBounds(230, 280, 276, 32);

        cmbComunidad.setFont(new java.awt.Font("Britannic Bold", 0, 12)); // NOI18N
        cmbComunidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cofradía", "El Habal", "El Pozole", "El Quelite", "El Recodo", "El Roble", "Mármol de Salcido", "Palmillas", "Potrerillos" }));
        cmbComunidad.setEnabled(false);
        jPanel1.add(cmbComunidad);
        cmbComunidad.setBounds(280, 430, 230, 33);

        btnCerrar.setBackground(new java.awt.Color(213, 247, 197));
        btnCerrar.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        btnCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/exit.png"))); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar);
        btnCerrar.setBounds(450, 690, 150, 40);

        txtUsuario.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario);
        txtUsuario.setBounds(230, 130, 276, 32);

        jLabel7.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(7, 68, 46));
        jLabel7.setText("Apellido(s)");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(60, 230, 122, 24);

        jLabel8.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(7, 68, 46));
        jLabel8.setText("Fecha");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(60, 90, 67, 24);

        jdcFecha.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        jPanel1.add(jdcFecha);
        jdcFecha.setBounds(230, 80, 187, 33);

        tblProveedor.setBackground(new java.awt.Color(46, 157, 137));
        tblProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProveedor.setToolTipText("");
        jScrollPane1.setViewportView(tblProveedor);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(120, 530, 590, 142);

        txtNombres.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        txtNombres.setEnabled(false);
        txtNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombresActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombres);
        txtNombres.setBounds(230, 180, 276, 32);

        txtRfc.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        txtRfc.setEnabled(false);
        txtRfc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRfcActionPerformed(evt);
            }
        });
        jPanel1.add(txtRfc);
        txtRfc.setBounds(230, 380, 276, 32);

        jLabel9.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(7, 68, 46));
        jLabel9.setText("Ahora eres parte de este proyecto!");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(210, 500, 399, 24);

        btnCancelar.setBackground(new java.awt.Color(213, 247, 197));
        btnCancelar.setFont(new java.awt.Font("Britannic Bold", 0, 18)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(220, 690, 150, 40);

        jLabel10.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(7, 68, 46));
        jLabel10.setText("Telefono");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(60, 330, 97, 24);

        txtTelefono.setFont(new java.awt.Font("Britannic Bold", 0, 14)); // NOI18N
        txtTelefono.setEnabled(false);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefono);
        txtTelefono.setBounds(230, 330, 276, 32);

        btnBorrar.setBackground(new java.awt.Color(213, 247, 197));
        btnBorrar.setFont(new java.awt.Font("Britannic Bold", 0, 12)); // NOI18N
        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/borrar.png"))); // NOI18N
        btnBorrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrar);
        btnBorrar.setBounds(640, 310, 80, 70);

        btnBuscar.setBackground(new java.awt.Color(213, 247, 197));
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/search.png"))); // NOI18N
        btnBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar);
        btnBuscar.setBounds(520, 130, 38, 38);

        btnNuevo.setBackground(new java.awt.Color(213, 247, 197));
        btnNuevo.setFont(new java.awt.Font("Britannic Bold", 0, 12)); // NOI18N
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/add.png"))); // NOI18N
        btnNuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(btnNuevo);
        btnNuevo.setBounds(640, 100, 80, 70);

        btnGuardar.setBackground(new java.awt.Color(213, 247, 197));
        btnGuardar.setFont(new java.awt.Font("Britannic Bold", 0, 12)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/save.png"))); // NOI18N
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar);
        btnGuardar.setBounds(640, 200, 80, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresActionPerformed

    private void txtRfcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRfcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRfcActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBorrar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JComboBox<String> cmbComunidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public com.toedter.calendar.JDateChooser jdcFecha;
    public javax.swing.JTable tblProveedor;
    public javax.swing.JTextField txtApellido;
    public javax.swing.JTextField txtCorreo;
    public javax.swing.JTextField txtNombres;
    public javax.swing.JTextField txtRfc;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
